####################
## bashmount.conf ##
####################

# Basics #
udisks='auto'                                                                         #set whether to use udisksctl '0', '1', or 'auto'
mount_options=''                                                                      #set default mount options. 

# Visibility #
show_internal='1'                                                                     #set which sections to show in the output. these can be '0' or '1'.
show_removable='1'
show_optical='1'
show_commands='1'
exclude=()                                                                            #set devices to exclude. Any device whose "lsblk -P" output contains a string listed here will be hidden.

# Aesthetics #
colourize='0'                                                                         #colourize the output. this can be '0' or '1'.
pretty='1'                                                                            #use unicode for pretty layout. This can be '0' or '1'.


# File Manager Options #

#filemanager() {
#   /usr/bin/nautilus "$1" & >/dev/null 2>&1                                          #set filemanager gui to use when performing the "open" command.(terminal if empty)
#}

filemanager() {                                                                       #launch lf in a new window.
   /usr/bin/foot -e /usr/bin/lf "$1" & >/dev/null 2>&1
}

# Custom Buttons #

#custom4_show='0'                                                                     #1 to enable
#custom4_desc='changeme'                                                              #name of function
#custom4_command() {
#    sudo mount --options remount,ro "$1" "/mnt/${1##*/}"
#}

#custom5_show='0'                                                                     #1 to enable
#custom5_desc='changeme'                                                              #name of function
#custom5_command() {
#
#}

#custom6_show='0'                                                                     #1 to enable
#custom6_desc='changeme'
#custom6_command() {
#
#}


# Custom On-Mount Commands #

#run_post_mount='0'                                                                   #1 to enable

#post_mount() {
#
#}


# Custom On-Unmount Commands #

#run_post_unmount='0'                                                                 #1 to enable

#post_unmount() {
#
#}
