################
##  HYPRIDLE  ##
################

general {
    lock_cmd = pidof hyprlock || hyprlock                                   #prevents multiple instances of Hyprland opening
}

listener {
    timeout = 600                                                           #in seconds
    on-resume = notify-send -t 500 "Welcome back stalker, good luck"        #message sent on login
    on-timeout = loginctl lock-session                                      #lock pc on timeout
}
