wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/moon.png
    fit_mode = contain
}

wallpaper {
    monitor = HDMI-A-1#
    path = ~/Pictures/wallpapers/moon.png 
    fit_mode = contain
}

  splash = false