###############
## HYPRPAPER ##
###############

# Main Monitor #
wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/moon.png
    fit_mode = contain
}

# Second Monitor #
wallpaper {
    monitor = HDMI-A-1#
    path = ~/Pictures/wallpapers/moon.png 
    fit_mode = contain
}

# Dumb Splash Message #
  splash = false
