###############
## HYPSUNSET ##
###############

profile {                                         #default daytime normal settings
    time = 7:30                                   #activates from 7:30am
    identity = true                               #ignore temp settings and sets default
}

profile {                                         #super eyesaving mode
    time = 03:00                                  #activates at 3:00am
    temperature = 3200                            #kelvin value (Lower=less blue)
    gamma = 0.7                                   #i used this as a shitty brightness adjuster
    identity = false                              #sets temperature settings
}
