#################
### AUTOSTART ###
#################

exec-once = swaync &                                             #Notification daemon
exec-once = hypridle &                                           #Starts timer for lockscreen (hyprlock)
exec-once = wal -R                                               #Refreshes Pywal on startup
exec-once = wl-paste --watch cliphist store                      #Starts clipboard log
exec-once = waypaper --restore                                   #Starts wallpaper wrapper
exec-once = swaybg                                               #Wallpaper daemon
exec-once = hyprsunset                                           #Blue-light filter
