###################
###  VARIABLES  ###
###################
$mainMod = SUPER

$terminal = foot
$fileManager = foot -e ~/bin/lfrun
$menu = rofi -show drun 
$browser = zen-browser
$textedit = code OSS

$wallpaper-path = ~/Pictures/wallpapers
$icon-path = ~/Pictures/icons
$desktop-logo-path = ~/Pictures/icons/logos


$current_time=$(date +"%H:%M")