##############################
###      WINDOWRULES	   ###
##############################

#################
##  DEF FIXES  ##
#################

windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*                                                   # Ignore maximize requests from apps. You'll probably like this.
}

windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0                                                      # Fix some dragging issues with XWayland
}

#######################
## Software Specific ##
#######################

windowrule {
    name = floating_steam_friends
    match:title = Friends List
    match:class = steam
    float = on
    move = 45 120
    size = 315 580
    max_size = 315 580
    min_size = 315 580
    no_initial_focus = on
  }

windowrule {
    name = floating_volume
    match:title = Volume Control
    match:class = org.pulseaudio.pavucontrol
    float = on
    move = 1125 1
    size = 793 354
  }
