##################
##  WORKSPACES  ##
##################

#WORKSPACE 1 - HOME
windowrule = workspace 1, match:class zen-browser-bin

#WORKSPACE 2 - BAR
windowrule = workspace 2,

#WORKSPACE 3 - TRACKS
windowrule = workspace 3, match:class code-oss

#WORKSPACE 4 - THE ZONE 01
windowrule = workspace 4, match:class steam


dwindle {
    pseudotile = true                                           # Master switch for pseudotiling.
    preserve_split = true                                       
}


master {
    new_status = master
}


misc {
    force_default_wallpaper = -1                                # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true                                # If true disables the random hyprland logo / anime girl background.
}
